// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlG1a5szIGS8KWysJZZVOMD_md9aRumeY',
    appId: '1:948388890570:web:11dd58b77246e002a6f133',
    messagingSenderId: '948388890570',
    projectId: 'trabalho-mobile-3',
    authDomain: 'trabalho-mobile-3.firebaseapp.com',
    storageBucket: 'trabalho-mobile-3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf7dj1WU3QG391VOkDQtN34zAl-hRMYbY',
    appId: '1:948388890570:android:23044b9451bc4beea6f133',
    messagingSenderId: '948388890570',
    projectId: 'trabalho-mobile-3',
    storageBucket: 'trabalho-mobile-3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkZ5zR1Vsp9NofLkCFJxPsa-3x0qU7x7s',
    appId: '1:948388890570:ios:9a08fc3e9808db69a6f133',
    messagingSenderId: '948388890570',
    projectId: 'trabalho-mobile-3',
    storageBucket: 'trabalho-mobile-3.firebasestorage.app',
    iosBundleId: 'com.example.myelenco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkZ5zR1Vsp9NofLkCFJxPsa-3x0qU7x7s',
    appId: '1:948388890570:ios:9a08fc3e9808db69a6f133',
    messagingSenderId: '948388890570',
    projectId: 'trabalho-mobile-3',
    storageBucket: 'trabalho-mobile-3.firebasestorage.app',
    iosBundleId: 'com.example.myelenco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlG1a5szIGS8KWysJZZVOMD_md9aRumeY',
    appId: '1:948388890570:web:ec7d1a146a8f0501a6f133',
    messagingSenderId: '948388890570',
    projectId: 'trabalho-mobile-3',
    authDomain: 'trabalho-mobile-3.firebaseapp.com',
    storageBucket: 'trabalho-mobile-3.firebasestorage.app',
  );
}
